In [2]:
import numpy as np
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(digits.data, digits.target, test_size = 0.3)

Logistic Regression

In [5]:
logistic_model = LogisticRegression(solver = 'liblinear', multi_class = 'ovr')
logistic_model.fit(x_train, y_train)
logistic_model.score(x_test, y_test)

0.9740740740740741

SVM

In [7]:
svm_model = SVC(gamma = 'auto')
svm_model.fit(x_train, y_train)
svm_model.score(x_test, y_test)

0.3648148148148148

Random Forest

In [10]:
forest_model = RandomForestClassifier(n_estimators = 30)
forest_model.fit(x_train, y_train)
forest_model.score(x_test, y_test)

0.9814814814814815

KFold basic implementation

In [12]:
def get_score(model, X_train, X_test, y_train, y_test):
    model.fit(X_train, y_train)
    return model.score(X_test, y_test)

from sklearn.model_selection import StratifiedKFold
folds = StratifiedKFold(n_splits=3)

scores_logistic = []
scores_svm = []
scores_rf = []

for train_index, test_index in folds.split(digits.data,digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    scores_logistic.append(get_score(LogisticRegression(solver='liblinear',multi_class='ovr'), X_train, X_test, y_train, y_test))  
    scores_svm.append(get_score(SVC(gamma='auto'), X_train, X_test, y_train, y_test))
    scores_rf.append(get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test))

In [13]:
scores_logistic

[0.8953488372093024, 0.9499165275459098, 0.9093959731543624]

In [14]:
scores_svm

[0.39368770764119604, 0.41068447412353926, 0.4597315436241611]

In [15]:
scores_rf

[0.920265780730897, 0.9515859766277128, 0.9211409395973155]

cross_val_score Function

In [18]:
from sklearn.model_selection import cross_val_score
cross_val_score(LogisticRegression(solver = 'liblinear', multi_class='ovr'), digits.data, digits.target, cv = 3)

array([0.89534884, 0.94991653, 0.90939597])

In [20]:
from sklearn.model_selection import cross_val_score
cross_val_score(SVC(gamma = 'auto'), digits.data, digits.target, cv = 3)

array([0.39368771, 0.41068447, 0.45973154])

In [24]:
from sklearn.model_selection import cross_val_score
cross_val_score(RandomForestClassifier(n_estimators = 30), digits.data, digits.target, cv = 3)

array([0.92524917, 0.94657763, 0.91442953])