In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('homeprices.csv')

In [3]:
df

area   price
0  2600  550000
1  3000  565000
2  3200  610000
3  3600  680000
4  4000  725000

In [5]:
reg = linear_model.LinearRegression()
reg.fit(df[['area']], df.price)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [6]:
reg.predict([[5000]])

array([859554.79452055])

In [7]:
import pickle

with open('model_pickle', 'wb') as f:
    pickle.dump(model, f)

In [9]:
with open('model_pickle', 'wb') as f:
    pickle.dump(reg, f)

In [10]:
with open('model_pickle', 'rb') as f:
    mp = pickle.load(f)

In [11]:
mp.predict([[5000]])

array([859554.79452055])

In [14]:
import joblib
joblib.dump(reg, 'model_joblib')

['model_joblib']

In [15]:
mj = joblib.load('model_joblib')

In [16]:
mj.predict([[5000]])

array([859554.79452055])